language: android

android:
  components:
    - tools
    - build-tools-26.0.2
    - android-25
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

notifications:
  email: false

sudo: false

env:
  global:
    - GRADLE_OPTS="-Xms128m"

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

script:
  - ./gradlew checkstyle assembleRelease test